from typing import List

DEFAULT_KEYWORDS: List[str] = [
    "tech",
    "technology",
    "artificial intelligence",
    "ai",
    "ai agents",
    "genai",
    "gpt",
    "software development",
    "developers",
    "programming",
    "open ai",
    "openai",
    "microsoft",
    "google",
    "amazon",
    "aws",
    "azure",
    "machine learning",
    "deep learning",
    "robotics",
    "automation",
    "agents",
    "langchain",
    "llm",
    "nvidia",
    "meta",
    "anthropic",
    "databricks",
    "snowflake",
    "hugging face",
    "cloud",
    "kubernetes",
    "docker",
    "devops",
    "sre",
    "observability",
    "security",
    "cybersecurity",
    "data engineering",
    "mlops",
    "windsurf",
    "cursor",
]
